name: Xcode Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Set Default Scheme
        id: set-scheme
        run: |
          default=$(xcodebuild -list -json | jq -r '.project.schemes[]' | grep -v Tests | head -1)
          echo "scheme=${default}" >> $GITHUB_ENV
          echo "Selected scheme: $default"

      - name: Build & Analyze
        run: |
          set -eo pipefail
          scheme="${{ env.scheme }}"
          # 自动检测项目类型
          if [ -n "$(ls | grep \.xcworkspace)" ]; then
            project_file="$(ls | grep \.xcworkspace | head -1)"
            flag="-workspace"
          else
            project_file="$(ls | grep \.xcodeproj | head -1)"
            flag="-project"
          fi
          xcodebuild clean build \
            $flag "$project_file" \
            -scheme "$scheme" \
            -destination "platform=macOS" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_ALLOWED=NO \
            2>&1 | tee xcodebuild.log

      - name: Upload Logs on Failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: xcodebuild-logs
          path: xcodebuild.log
