name: Xcode Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Set Default Scheme
        id: set-scheme
        run: |
          default=$(xcodebuild -list -json | jq -r '.project.schemes[]' | grep -v Tests | head -1)
          echo "scheme=${default}" >> $GITHUB_ENV
          echo "Selected scheme: $default"

      - name: Build & Package
        run: |
          set -eo pipefail
          scheme="${{ env.scheme }}"

          # 目录设置
          BUILD_DIR="$PWD/build_artifacts"
          OUTPUT_DIR="$PWD/output"
          mkdir -p $BUILD_DIR $OUTPUT_DIR

          # 检测项目文件
          if [ -n "$(ls | grep \.xcworkspace)" ]; then
            project_file="$(ls | grep \.xcworkspace | head -1)"
            flag="-workspace"
          else
            project_file="$(ls | grep \.xcodeproj | head -1)"
            flag="-project"
          fi

          # 构建
          xcodebuild clean build \
            $flag "$project_file" \
            -scheme "$scheme" \
            -destination "platform=macOS" \
            -derivedDataPath $BUILD_DIR \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_ALLOWED=NO \
            2>&1 | tee xcodebuild.log

          # 拷贝所有.app到临时目录
          mkdir "$OUTPUT_DIR/flat_apps"
          find "$BUILD_DIR/Build/Products" -name "*.app" \
            -exec sh -c 'cp -R "$0" "$OUTPUT_DIR/flat_apps/$(basename "$0")"' {} \;

          # 直接压缩整个目录（保留平面结构）
          (cd "$OUTPUT_DIR/flat_apps" && tar -czvf ../app_bundle.tar.gz ./*)
          echo "APP_BUNDLE=$OUTPUT_DIR/app_bundle.tar.gz" >> $GITHUB_ENV

      - name: Upload Logs on Failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: xcodebuild-logs
          path: xcodebuild.log

      # 新增：上传构建产物
      - name: Upload Build Artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: ${{ env.APP_BUNDLE }}
          retention-days: 3 # 自动保留3天
